
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 08 22:16:51 MDT 2022
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OpAgrup_LlaveApert = 46;
  public static final int OpLog_Not = 41;
  public static final int PR_Exeption = 8;
  public static final int PR_Filamenttype = 61;
  public static final int Op_Decremento = 38;
  public static final int PR_Port = 75;
  public static final int PR_Drawrectangulo = 73;
  public static final int OpLog_Or = 40;
  public static final int PR_Catch = 2;
  public static final int PR_Setfilamenttype = 62;
  public static final int OpRel_Mayor = 32;
  public static final int PR_Default = 5;
  public static final int PR_Option = 16;
  public static final int SimbEsp_Coma = 56;
  public static final int OpRel_Diferente = 36;
  public static final int PR_False = 24;
  public static final int OpRel_MayorIgual = 35;
  public static final int OpAritm_Resto = 30;
  public static final int PR_Fillrectangulo = 70;
  public static final int SimbEsp_Punto = 55;
  public static final int SimbEsp_Comilla = 54;
  public static final int OpAgrup_LlaveCierre = 47;
  public static final int OpAritm_Resta = 27;
  public static final int PR_Word = 22;
  public static final int PR_Class = 3;
  public static final int PR_Interruption = 13;
  public static final int PR_Def = 4;
  public static final int PR_Draw = 69;
  public static final int PR_While = 21;
  public static final int ERROR5 = 80;
  public static final int ERROR4 = 79;
  public static final int Numero_Exact = 53;
  public static final int ERROR3 = 78;
  public static final int ERROR2 = 77;
  public static final int PR_Setextrusorz = 68;
  public static final int ERROR1 = 76;
  public static final int PR_Setextrusory = 67;
  public static final int PR_Setextrusorx = 66;
  public static final int OpAgrup_CorchApert = 44;
  public static final int OpRel_Igual = 33;
  public static final int PR_Stop = 59;
  public static final int PR_Sleep = 60;
  public static final int PR_Part = 17;
  public static final int Simbolo_Especial = 58;
  public static final int OpAritm_Mult = 28;
  public static final int SimbEsp_DosPuntos = 57;
  public static final int OpAritm_Div = 29;
  public static final int OpAgrup_ParApert = 42;
  public static final int OpRel_Menor = 31;
  public static final int PR_Getextrusorz = 65;
  public static final int EOF = 0;
  public static final int PR_Getextrusory = 64;
  public static final int OpAritm_Suma = 26;
  public static final int PR_Getextrusorx = 63;
  public static final int OpAgrup_ParCierre = 43;
  public static final int PR_For = 10;
  public static final int PR_True = 23;
  public static final int OpLog_And = 39;
  public static final int OpAsig = 48;
  public static final int PR_Filltriangulo = 71;
  public static final int PR_If = 11;
  public static final int PR_Fillcirculo = 72;
  public static final int PR_Try = 18;
  public static final int PuntoComa = 49;
  public static final int PR_Flag = 9;
  public static final int error = 1;
  public static final int PR_Home = 74;
  public static final int PR_Void = 20;
  public static final int PR_Ing = 12;
  public static final int PR_Else = 6;
  public static final int PR_Switch = 19;
  public static final int Identificador = 50;
  public static final int PR_Return = 25;
  public static final int PR_Exact = 7;
  public static final int PR_Imp = 14;
  public static final int OpAgrup_CorchCierre = 45;
  public static final int Op_Incremento = 37;
  public static final int PR_Main = 15;
  public static final int Numero_Part = 52;
  public static final int OpRel_MenorIgual = 34;
  public static final int Cadena_texto = 51;
}

